### ISSUE TITLE
autotune crash

### ISSUE THREAD

**Issue by joefowler** [usnistgov/quantum-sensors-tdm#1]
**[Original report](https://bitbucket.org/nist_microcal/nist-qsp-tdm/issues/1) by Galen O'Neil (Bitbucket: [oneilg](https://bitbucket.org/oneilg), GitHub: [oneilg](https://github.com/oneilg)).**

----------------------------------------

```
Traceback (most recent call last):
  File "/home/pcuser/qsp/src/nistqsptdm/cringe/tune/tunetab.py", line 315, in fullTune
    fbbstats = vphistats.vPhiStats(fbbtriangle, fbbsigsup)
  File "/home/pcuser/qsp/src/nistqsptdm/cringe/tune/vphistats.py", line 71, in vPhiStats
    stattuple = vPhiStatsSingle(triangle, signals[col,row], fracFromBottom)
  File "/home/pcuser/qsp/src/nistqsptdm/cringe/tune/vphistats.py", line 48, in vPhiStatsSingle
    firstMinimumInd = np.argmin(signaloneperiod)
  File "<__array_function__ internals>", line 6, in argmin
  File "/home/pcuser/qsp/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1267, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/home/pcuser/qsp/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
```

‌

**Comment by joefowler** [comment]
**Original comment by Galen O'Neil (Bitbucket: [oneilg](https://bitbucket.org/oneilg), GitHub: [oneilg](https://github.com/oneilg)).**

----------------------------------------

another crash, seems different

```

INFO: ZmqRep: resolve_message: reply: `ok: `
INFO: ZmqRep: emit_if_has_message: got: FULL_TUNE
INFO: start fbb vphi
Traceback (most recent call last):
  File "/home/pcuser/qsp/src/nistqsptdm/cringe/tune/tunetab.py", line 314, in fullTune
    fbbtriangle, fbbsigsup, fbbsigsdown = self.FBBvphi()
  File "/home/pcuser/qsp/src/nistqsptdm/cringe/tune/tunetab.py", line 243, in FBBvphi
    data = self.c.getNewData(0.1, minimumNumPoints=4096*6)
  File "/home/pcuser/qsp/src/nistqsptdm/nasa_client/easyClientDastard.py", line 247, in getNewData
    header, data = self.getMessage()
  File "/home/pcuser/qsp/src/nistqsptdm/nasa_client/easyClientDastard.py", line 187, in getMessage
    h, m = self.recordSub.recv_multipart()
  File "/home/pcuser/qsp/lib/python3.6/site-packages/zmq/sugar/socket.py", line 475, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 20, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

```

‌

**Comment by joefowler** [comment]
**Original comment by Paul Szypryt (Bitbucket: [pszypryt](https://bitbucket.org/pszypryt), GitHub: [pszypryt](https://github.com/pszypryt)).**

----------------------------------------

another one

```
Traceback (most recent call last):
  File "/home/pcuser/qsp/src/nistqsptdm/cringe/tune/analysis.py", line 65, in conditionvphis
    triout, sigup, sigdown = conditionvphi(triangle[col, row, :], signal[col, row, :], tridwell, tristeps, tristepsize)
  File "/home/pcuser/qsp/src/nistqsptdm/cringe/tune/analysis.py", line 41, in conditionvphi
    raise Exception("triangle appears imperfect")
Exception: triangle appears imperfect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pcuser/qsp/src/nistqsptdm/cringe/tune/tunetab.py", line 314, in fullTune
    fbbtriangle, fbbsigsup, fbbsigsdown = self.FBBvphi()
  File "/home/pcuser/qsp/src/nistqsptdm/cringe/tune/tunetab.py", line 248, in FBBvphi
    outtriangle, outsigsup, outsigsdown = analysis.conditionvphis(data[:,:,:,1], data[:,:,:,0], tridwell, tristeps, tristepsize)
  File "/home/pcuser/qsp/src/nistqsptdm/cringe/tune/analysis.py", line 67, in conditionvphis
    raise type(ex)("{}, col {}, row {}".format(ex,col,row))
Exception: triangle appears imperfect, col 7, row 22
```

‌
