### ISSUE TITLE
adr_gui: zaber related crash observed on dixie

### ISSUE THREAD

**Issue by joefowler** [usnistgov/quantum-sensors-tdm#8]
**[Original report](https://bitbucket.org/nist_microcal/nist-qsp-tdm/issues/8) by Galen O'Neil (Bitbucket: [oneilg](https://bitbucket.org/oneilg), GitHub: [oneilg](https://github.com/oneilg)).**

----------------------------------------

```
Traceback (most recent call last):
  File "/home/pcuser/qsp/src/nistqsptdm/adr_gui/adr_gui.py", line 390, in timerHandler
    self.stateTick()
  File "/home/pcuser/qsp/src/nistqsptdm/adr_gui/adr_gui.py", line 479, in stateTick
    self.holdAfterMagUpStateTick()
  File "/home/pcuser/qsp/src/nistqsptdm/adr_gui/adr_gui.py", line 546, in holdAfterMagUpStateTick
    self.ensureHeatSwitchIsOpen()
  File "/home/pcuser/qsp/src/nistqsptdm/adr_gui/adr_gui.py", line 377, in ensureHeatSwitchIsOpen
    self.tempControl.a.heat_switch.OpenHeatSwitch()
  File "/home/pcuser/qsp/src/nistqsptdm/instruments/zaber.py", line 192, in OpenHeatSwitch
    self.SetRunningCurrent(self.OpeningCurrent)
  File "/home/pcuser/qsp/src/nistqsptdm/instruments/zaber.py", line 175, in SetRunningCurrent
    self.__sendCommandParseReply(value=current, command=38)
  File "/home/pcuser/qsp/src/nistqsptdm/instruments/zaber.py", line 109, in __sendCommandParseReply
    return self.__parseReplyToInt(command, reply, value)
  File "/home/pcuser/qsp/src/nistqsptdm/instruments/zaber.py", line 128, in __parseReplyToInt
    raise Exception(self.__errorString(v, command, command_value))
Exception: zaber command 38 with data 10 failed with code 15: voltage high
Aborted (core dumped)
```

‌

**Comment by joefowler** [comment]
**Original comment by Galen O'Neil (Bitbucket: [oneilg](https://bitbucket.org/oneilg), GitHub: [oneilg](https://github.com/oneilg)).**

----------------------------------------

Saw it again today, here is the backtrace

‌

```
heat switch ensure open
heat switch closed, opening
Traceback (most recent call last):
  File "/home/pcuser/qsp/src/nistqsptdm/adr_gui/adr_gui.py", line 390, in timerHandler
    self.stateTick()
  File "/home/pcuser/qsp/src/nistqsptdm/adr_gui/adr_gui.py", line 479, in stateTick
    self.holdAfterMagUpStateTick()
  File "/home/pcuser/qsp/src/nistqsptdm/adr_gui/adr_gui.py", line 546, in holdAfterMagUpStateTick
    self.ensureHeatSwitchIsOpen()
  File "/home/pcuser/qsp/src/nistqsptdm/adr_gui/adr_gui.py", line 377, in ensureHeatSwitchIsOpen
    self.tempControl.a.heat_switch.OpenHeatSwitch()
  File "/home/pcuser/qsp/src/nistqsptdm/instruments/zaber.py", line 192, in OpenHeatSwitch
    self.SetRunningCurrent(self.OpeningCurrent)
  File "/home/pcuser/qsp/src/nistqsptdm/instruments/zaber.py", line 175, in SetRunningCurrent
    self.__sendCommandParseReply(value=current, command=38)
  File "/home/pcuser/qsp/src/nistqsptdm/instruments/zaber.py", line 109, in __sendCommandParseReply
    return self.__parseReplyToInt(command, reply, value)
  File "/home/pcuser/qsp/src/nistqsptdm/instruments/zaber.py", line 128, in __parseReplyToInt
    raise Exception(self.__errorString(v, command, command_value))
Exception: zaber command 38 with data 10 failed with code 15: voltage high
Aborted (core dumped)
```

‌

**Comment by NanoExplorer** [comment]
Did commit 2fe3680 fix this issue?

**Comment by ggggggggg** [comment]
Yes
________________________________
